version: "3"
services:
  app:
    env_file: .env
    build: .
    depends_on:
      - postgres
    network_mode: "host"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: "host"

networks:
  host:
    name: host
    external: true