version: "3"

volumes:
  postgres:
    driver: local

services:
  app:
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres